### ISSUE TITLE
Docs: Tidy/Enhance `README.md` ready for Open Source

### ISSUE THREAD

**Issue by nelsonic** [alpheya/sealed-secrets-ui#2]
As noted in https://github.com/quantum-wealth/docs/issues/46 we want to Open Source as much non "secret sauce" code/components as possible to _invite_ contribution from the coding community. 
Sealed Secrets are a great candidate for Open Source because they are _generally_ useful to most teams/projects/companies and not at all specific to us. 
With this in mind, we need to review the `README.md` of this project and tidy+enhance it for `public` consumption to answer as many common "onboarding" questions as possible and streamline the process of running/deploying the UI. 

# Todo

+ [ ] Review the `README.md` with a [beginner's mind](https://en.wikipedia.org/wiki/Shoshin) 🔰 
+ [ ] Answer any questions _we_ have while reading it.
  + [ ] Why? 
  + [ ] What?
  + [ ] Who?
  + [ ] _How_?
+ [ ] Run the app on `localhost` as fill-in any gaps in the setup instructions - this is the baseline for contribution.
+ [ ] Describe how to deploy to _our_ (internal) infra 
+ [ ] Show how to deploy to _alternative_ cloud and/or on-prem
+ [ ] Describe how people can _contribute_ if appropriate

# Bonus Level

+ [ ] Add `GitHub CI` to test the code.
+ [ ] Add necessary **`tests`** to gain confidence that nothing will _break_ when people contribute.
+ [ ] Add in-line comments as needed to clarify any `code` (not much)
+ [ ] Refactor as needed to make functions testable (don't think much is necessary)

**Comment by nelsonic** [comment]
Add link to: https://youtu.be/E0F4usFauvc
